services:
  tgbot:
    build: .
    container_name: sheerid-tgbot
    restart: unless-stopped

    # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
      # Telegram Bot 配置
      - BOT_TOKEN=8481639648:AAHlz7j-2CacDTJZgbm0vXeSDSKx2a7Tahw
      - CHANNEL_USERNAME=sheerid01
      - CHANNEL_URL=https://t.me/sheeeid01
      - ADMIN_USER_ID=792031112
      # MySQL配置
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_USER=tgbot
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=tgbot

    # 日志持久化
    volumes:
      - ./logs:/app/logs

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 网络模式
    network_mode: bridge
